spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/rolling
    username: ${USERNAME}
    password: ${PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show-sql: true