spring:
  data:
    redis:
      host: localhost
      port: 6379
  datasource:
    url: jdbc:mariadb://localhost:3306/rolling
    username: ${USERNAME}
    password: ${PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show-sql: true

jwt:
  secret: ${SECRET}
  refresh-token-seconds: 1209600 #14일
  access-token-seconds: 43200 #12시간