spring:
  mail:
    host: smtp.naver.com
    port: 465
    username: ab8c1c1d244f7bfb2d8c9f9b6e98b5ad5e8e7f682621432b49545d4b7e78f0f6
    password: ab8c1c1d244f7bfb2d8c9f9b6e98b5ad5e8e7f682621432b49545d4b7e78f0f6
    properties:
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true
      mail.smtp.ssl.trust: smtp.naver.com
  data:
    redis:
      host: localhost
      port: 6379
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ab8c1c1d244f7bfb2d8c9f9b6e98b5ad5e8e7f682621432b49545d4b7e78f0f6
            client-secret: ab8c1c1d244f7bfb2d8c9f9b6e98b5ad5e8e7f682621432b49545d4b7e78f0f6
            scope:
              - email
              - profile
          naver:
            client-id: ab8c1c1d244f7bfb2d8c9f9b6e98b5ad5e8e7f682621432b49545d4b7e78f0f6
            client-secret: ab8c1c1d244f7bfb2d8c9f9b6e98b5ad5e8e7f682621432b49545d4b7e78f0f6
            scope: name, email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
          kakao:
            client-id: ab8c1c1d244f7bfb2d8c9f9b6e98b5ad5e8e7f682621432b49545d4b7e78f0f6
            client-secret: ab8c1c1d244f7bfb2d8c9f9b6e98b5ad5e8e7f682621432b49545d4b7e78f0f6
            scope: profile_nickname, account_email
            client-name: Kakao
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            client-authentication-method: POST
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

#AWS 설정
cloud:
  aws:
    credentials:
      access-key: ab8c1c1d244f7bfb2d8c9f9b6e98b5ad5e8e7f682621432b49545d4b7e78f0f6
      secret-key: ab8c1c1d244f7bfb2d8c9f9b6e98b5ad5e8e7f682621432b49545d4b7e78f0f6
    s3:
      bucket: ab8c1c1d244f7bfb2d8c9f9b6e98b5ad5e8e7f682621432b49545d4b7e78f0f6
    region:
      static: ap-northeast-2
    stack:
      auto: false

#JWT 설정
jwt:
  secret: ab8c1c1d244f7bfb2d8c9f9b6e98b5ad5e8e7f682621432b49545d4b7e78f0f6 #프로젝트의 실제 secret과 다르게 설정
  refresh-token-seconds: 1209600 #14일
  access-token-seconds: 43200 #12시간